/// Design System: a Material 3 based Flutter component library.
///
/// White-label by default: build your theme with [DsTheme.light] /
/// [DsTheme.dark], optionally passing your own [DsTokens] to re-brand every
/// component at once.
library;

// Tokens
export 'src/tokens/ds_breakpoints.dart';
export 'src/tokens/ds_chart_palette.dart';
export 'src/tokens/ds_colors.dart';
export 'src/tokens/ds_elevation.dart';
export 'src/tokens/ds_icon_size.dart';
export 'src/tokens/ds_icons.dart';
export 'src/tokens/ds_radii.dart';
export 'src/tokens/ds_spacing.dart';
export 'src/tokens/ds_typography.dart';

// Theme
export 'src/theme/ds_skins.dart';
export 'src/theme/ds_theme.dart';
export 'src/theme/ds_tokens_extension.dart';

// Utilities
export 'src/util/ds_input_masks.dart';
export 'src/util/ds_motion.dart';
export 'src/util/ds_validators.dart';
export 'src/util/ds_validators_za.dart';

// Components, organised by Atomic Design layer.
//
// Atoms
export 'src/components/atoms/ds_animated_ellipsis.dart';
export 'src/components/atoms/ds_auth_gradient.dart';
export 'src/components/atoms/ds_avatar.dart';
export 'src/components/atoms/ds_back_link.dart';
export 'src/components/atoms/ds_badge.dart';
export 'src/components/atoms/ds_box.dart';
export 'src/components/atoms/ds_brand_bloom.dart';
export 'src/components/atoms/ds_button.dart';
export 'src/components/atoms/ds_checkbox.dart';
export 'src/components/atoms/ds_chip.dart';
export 'src/components/atoms/ds_choice_chip.dart';
export 'src/components/atoms/ds_divider.dart';
export 'src/components/atoms/ds_fade_slide_in.dart';
export 'src/components/atoms/ds_field_label.dart';
export 'src/components/atoms/ds_heading_alignment.dart';
export 'src/components/atoms/ds_check_dot.dart';
export 'src/components/atoms/ds_icon.dart';
export 'src/components/atoms/ds_key_hint.dart';
export 'src/components/atoms/ds_icon_badge.dart';
export 'src/components/atoms/ds_icon_button.dart';
export 'src/components/atoms/ds_img.dart';
export 'src/components/atoms/ds_inline.dart';
export 'src/components/atoms/ds_link.dart';
export 'src/components/atoms/ds_nav_link.dart';
export 'src/components/atoms/ds_progress_bar.dart';
export 'src/components/atoms/ds_radio.dart';
export 'src/components/atoms/ds_scroll_fade.dart';
export 'src/components/atoms/ds_segmented_control.dart';
export 'src/components/atoms/ds_shake.dart';
export 'src/components/atoms/ds_spinner.dart';
export 'src/components/atoms/ds_stat_tile.dart';
export 'src/components/atoms/ds_sparkline.dart';
export 'src/components/atoms/ds_step_header.dart';
export 'src/components/atoms/ds_switch.dart';
export 'src/components/atoms/ds_wordmark.dart';
// Molecules
export 'src/components/molecules/ds_accordion.dart';
export 'src/components/molecules/ds_action_tile.dart';
export 'src/components/molecules/ds_address_field_group.dart';
export 'src/components/molecules/ds_banner.dart';
export 'src/components/molecules/ds_button_group.dart';
export 'src/components/molecules/ds_coachmark.dart';
export 'src/components/molecules/ds_cookie_banner.dart';
export 'src/components/molecules/ds_chip_group.dart';
export 'src/components/molecules/ds_radio_group.dart';
export 'src/components/molecules/ds_currency_field.dart';
export 'src/components/molecules/ds_date_field.dart';
export 'src/components/molecules/ds_dialog.dart';
export 'src/components/molecules/ds_dropzone.dart';
export 'src/components/molecules/ds_empty_state.dart';
export 'src/components/molecules/ds_expiry_date.dart';
export 'src/components/molecules/ds_filter_chip.dart';
export 'src/components/molecules/ds_floating_bar.dart';
export 'src/components/molecules/ds_footer_actions.dart';
export 'src/components/molecules/ds_form_field_group.dart';
export 'src/components/molecules/ds_import_guide.dart';
export 'src/components/molecules/ds_inline_notice.dart';
export 'src/components/molecules/ds_key_value_row.dart';
export 'src/components/molecules/ds_labeled_divider.dart';
export 'src/components/molecules/ds_list_item.dart';
export 'src/components/molecules/ds_menu.dart';
export 'src/components/molecules/ds_menu_sheet.dart';
export 'src/components/molecules/ds_page_header.dart';
export 'src/components/molecules/ds_pagination.dart';
export 'src/components/molecules/ds_password_field.dart';
export 'src/components/molecules/ds_password_requirements.dart';
export 'src/components/molecules/ds_password_strength.dart';
export 'src/components/molecules/ds_resend_control.dart';
export 'src/components/molecules/ds_phone_field.dart';
export 'src/components/molecules/ds_search_field.dart';
export 'src/components/molecules/ds_select.dart';
export 'src/components/molecules/ds_status_legend.dart';
export 'src/components/molecules/ds_summary_section.dart';
export 'src/components/molecules/ds_tabs.dart';
export 'src/components/molecules/ds_text_area.dart';
export 'src/components/molecules/ds_timeline.dart';
export 'src/components/molecules/ds_time_field.dart';
export 'src/components/molecules/ds_text_field.dart';
export 'src/components/molecules/ds_toast.dart';
export 'src/components/atoms/ds_tooltip.dart';
export 'src/components/molecules/ds_upload_field.dart';
export 'src/components/molecules/ds_verification_rail.dart';
// Organisms
export 'src/components/organisms/ds_bar_chart.dart';
export 'src/components/organisms/ds_bottom_nav.dart';
export 'src/components/organisms/ds_board_view.dart';
export 'src/components/organisms/ds_business_verification.dart';
export 'src/components/organisms/ds_context_view.dart';
export 'src/components/organisms/ds_cookie_preferences.dart';
export 'src/components/organisms/ds_data_grid.dart';
export 'src/components/organisms/ds_data_table.dart';
export 'src/components/organisms/ds_detail_panel.dart';
export 'src/components/organisms/ds_filter_bar.dart';
export 'src/components/organisms/ds_focus_view.dart';
export 'src/components/organisms/ds_import_wizard.dart';
export 'src/components/organisms/ds_intro_card.dart';
export 'src/components/organisms/ds_line_chart.dart';
export 'src/components/molecules/ds_list.dart';
export 'src/components/molecules/ds_meter_chart.dart';
export 'src/components/organisms/ds_nav_rail.dart';
export 'src/components/organisms/ds_onboarding_wizard.dart';
export 'src/components/organisms/ds_policy_builder.dart';
export 'src/components/molecules/ds_progress_stepper.dart';
export 'src/components/organisms/ds_choose_password_view.dart';
export 'src/components/organisms/ds_forgot_password_view.dart';
export 'src/components/organisms/ds_record_panel.dart';
export 'src/components/organisms/ds_roster_view.dart';
export 'src/components/organisms/ds_settings_view.dart';
export 'src/components/organisms/ds_setup_guide.dart';
export 'src/components/organisms/ds_sign_in_view.dart';
export 'src/components/organisms/ds_sign_up_view.dart';
export 'src/components/organisms/ds_sort_builder.dart';
export 'src/components/organisms/ds_sort_pill.dart';
export 'src/components/organisms/ds_spotlight.dart';
export 'src/components/organisms/ds_status_bar.dart';
export 'src/components/organisms/ds_takeover.dart';
export 'src/components/organisms/ds_tour_card.dart';
export 'src/components/organisms/ds_top_nav.dart';
export 'src/components/organisms/ds_tree_view.dart';
export 'src/components/organisms/ds_verify_email_card.dart';
export 'src/components/organisms/ds_waiting_screen.dart';
// Templates
export 'src/components/templates/ds_app_shell.dart';
export 'src/components/templates/ds_auth_shell.dart';
export 'src/components/templates/ds_page_scaffold.dart';
export 'src/components/templates/ds_task_view.dart';
